### PR TITLE
New option ignoreFilesNotFound

### PR DESCRIPTION
**Pull request by lneves12**
Added a new option 'ignoreNotFoundFiles' so the plugin can keep going even if it find a nonexistent file

### CODE REVIEW

**Comment by gabrielflorit** [comment]
Hi @lneves12, this looks good, thanks for the addition. I'll take a closer look in the morning, will merge soon.

**Comment by gabrielflorit** [comment]
This is good - thanks for adding tests and documentation, much appreciated!

**Comment by lneves12** [comment]
Thanks for the fast merge :+1:   :) I corrected a small detail caused by my refactoring in this commit https://github.com/lneves12/gulp-smoosher/commit/0886c878db1d462bb4cbc2e9f4d48b941b05b822 - It doesn't have impact but you can add it in a future release if you want!

**Comment by gabrielflorit** [comment]
Hmm, it seems there's a mix of

`callback(error)`

and

`return callback(error)`

throughout the code, this is before your work. I wonder what's the right approach.

**Comment by lneves12** [comment]
I guess 'return callback(error)' would be more correct when we have errors to avoid mistakes, so it doesn't try to execute the rest of the function.

**Pull request merged**
